name: Build Docker image
# This workflow is triggered 1st, 16th and 31st
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
jobs:
  build:
    name: latest
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: SSH connection to Actions
       uses: P3TERX/ssh2actions@v1.0.0
       if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')     
     - name: Build image
       run: |
        cd phicomm-n1 && ./compile.sh BOARD=arm-64 BRANCH=current RELEASE=buster BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,img

     - name: xz
       run: cd phicomm-n1 && xz -9kv output/images/*.img
     
     - name: upload to artifact
       uses: actions/upload-artifact@main
       with:
         name: armbian
         path: phicomm-n1/output/images/*.img.xz

